services:
  ocr-meter-store:
    build: .
    image: ocr-meter-store:2.0.0
    container_name: ocr-meter-store
    restart: unless-stopped
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - BASE_PATH_PREFIX=/iot
    volumes:
      - ocr_images:/data/images
    networks:
      - innovation_net

volumes:
  ocr_images:

networks:
  innovation_net:
    external: true
